In [1]:
from google.colab import drive
drive.mount('/content/drive/')
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt 
from matplotlib.image import imread
import warnings
warnings.filterwarnings("ignore")
import seaborn as sns
import glob

Mounted at /content/drive/

In [ ]:
sample_data = pd.read_csv('/content/drive/MyDrive/DatasetProject1/train_task_1_2.csv')

In [ ]:
answer_meta = pd.read_csv('/content/drive/MyDrive/DatasetProject1/answer_metadata_task_1_2.csv')

In [ ]:
question_meta = pd.read_csv('/content/drive/MyDrive/DatasetProject1/question_metadata_task_1_2.csv')

In [ ]:
student_meta = pd.read_csv('/content/drive/MyDrive/DatasetProject1/student_metadata_task_1_2.csv')

In [ ]:
subject_meta = pd.read_csv('/content/drive/MyDrive/DatasetProject1/subject_metadata.csv')

In [ ]:
sample_data_answer = sample_data.merge(answer_meta, how='left', on='AnswerId')
sample_data_answer.head()

   QuestionId  UserId  AnswerId  ...  GroupId  QuizId  SchemeOfWorkId
0       16997   65967  12453206  ...     5026   15391          8408.0
1       16531   62121  15686710  ...     9607    4681             NaN
2       15911   50013  13598796  ...     4975   17226         28228.0
3        1701  104909  10511925  ...     7393    7243             NaN
4       22896   21748    941747  ...     3734    5828             NaN

[5 rows x 11 columns]

In [ ]:
sample_data_answer_student = sample_data_answer.merge(student_meta, how='left', on='UserId')
sample_data_answer_student.head()

   QuestionId  UserId  AnswerId  ...  Gender              DateOfBirth  PremiumPupil
0       16997   65967  12453206  ...       1  2002-11-01 00:00:00.000           0.0
1       16531   62121  15686710  ...       1  2007-11-01 00:00:00.000           1.0
2       15911   50013  13598796  ...       1  2004-09-01 00:00:00.000           1.0
3        1701  104909  10511925  ...       1  2006-01-01 00:00:00.000           NaN
4       22896   21748    941747  ...       1                      NaN           NaN

[5 rows x 14 columns]

In [ ]:
from ast import literal_eval
question = []
#for index, row in df.iterrows():
for row in question_meta.itertuples(index=False):
  x = list (row)
  lis = list(literal_eval(x[1]))
  x.append (lis[-1] ) 
  a = x + lis
  question.append(a)

question = pd.DataFrame(question)
question.head()

      0                                    1    2   3   4   ...  12  13  14  15  16
0  13090  [3, 32, 71, 77, 141, 185, 186, 214]  214   3  32  ... NaN NaN NaN NaN NaN
1   1855                 [3, 71, 75, 86, 178]  178   3  71  ... NaN NaN NaN NaN NaN
2  10423                     [3, 32, 38, 239]  239   3  32  ... NaN NaN NaN NaN NaN
3   2290                     [3, 32, 33, 144]  144   3  32  ... NaN NaN NaN NaN NaN
4  12785                     [3, 32, 33, 144]  144   3  32  ... NaN NaN NaN NaN NaN

[5 rows x 17 columns]

In [ ]:
columns =['QuestionId','SubjectList','SubjectId','SubjectId_1','SubjectId_2','SubjectId_3','SubjectId_4','SubjectId_5','SubjectId_6','SubjectId_7','SubjectId_8','SubjectId_9','SubjectId_10','SubjectId_11','SubjectId_12','SubjectId_13','SubjectId_14']
question.columns = columns
question.head()

   QuestionId                          SubjectList  ...  SubjectId_13  SubjectId_14
0       13090  [3, 32, 71, 77, 141, 185, 186, 214]  ...           NaN           NaN
1        1855                 [3, 71, 75, 86, 178]  ...           NaN           NaN
2       10423                     [3, 32, 38, 239]  ...           NaN           NaN
3        2290                     [3, 32, 33, 144]  ...           NaN           NaN
4       12785                     [3, 32, 33, 144]  ...           NaN           NaN

[5 rows x 17 columns]

In [ ]:
sample_data_answer_student_question = sample_data_answer_student.merge(question, how='left', on='QuestionId')
sample_data_answer_student_question.head()

   QuestionId  UserId  AnswerId  ...  SubjectId_12  SubjectId_13  SubjectId_14
0       16997   65967  12453206  ...           NaN           NaN           NaN
1       16531   62121  15686710  ...           NaN           NaN           NaN
2       15911   50013  13598796  ...           NaN           NaN           NaN
3        1701  104909  10511925  ...           NaN           NaN           NaN
4       22896   21748    941747  ...           NaN           NaN           NaN

[5 rows x 30 columns]

In [ ]:
sample_data_answer_student_question_subject = sample_data_answer_student_question.merge(subject_meta, how='left', on='SubjectId')
sample_data_answer_student_question_subject.head()

   QuestionId  UserId  ...  ParentId  Level
0       16997   65967  ...     101.0      2
1       16531   62121  ...      71.0      2
2       15911   50013  ...      42.0      3
3        1701  104909  ...     144.0      3
4       22896   21748  ...     144.0      3

[5 rows x 33 columns]

In [ ]:
sample_data_answer_student_question_subject.to_csv('/content/drive/MyDrive/DatasetProject1/toPer.csv')

In [2]:
data = pd.read_csv('/content/drive/MyDrive/DatasetProject1/toPer.csv')
data.head()

   Unnamed: 0  QuestionId  ...  ParentId  Level
0           0       16997  ...     101.0      2
1           1       16531  ...      71.0      2
2           2       15911  ...      42.0      3
3           3        1701  ...     144.0      3
4           4       22896  ...     144.0      3

[5 rows x 34 columns]

In [3]:
data = data.drop(['Unnamed: 0','Name','SubjectList','SchemeOfWorkId','Confidence','SubjectId_14','SubjectId_13','SubjectId_12','SubjectId_11','SubjectId_10','SubjectId_9','SubjectId_8','SubjectId_7','SubjectId_6','SubjectId_5'],axis=1)

In [4]:
data['Gender']=data['Gender'].replace(3,0)

In [5]:
list(data['Gender'].unique())

[1, 0, 2]

In [6]:
data['DateOfBirth'] =pd.to_datetime(data['DateOfBirth'], errors = 'coerce')
data['DateAnswered'] =pd.to_datetime(data['DateAnswered'])

In [7]:
data['Age'] = (data['DateAnswered'] - data['DateOfBirth']) / np.timedelta64(1,'Y')

In [8]:
data.loc[data[data['Age'] < 6].index,'Age'] = 6
data.loc[data[data['Age'] > 45].index,'Age'] = 45
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [9]:
data['Age'] = data['Age'].astype(int)

In [10]:
data = data.fillna({'ParentId':0})
data['ParentId'] = data['ParentId'].astype(int)
list(data['ParentId'].unique())

[101,
 71,
 42,
 144,
 39,
 49,
 272,
 55,
 61,
 100,
 40,
 46,
 44,
 36,
 62,
 74,
 98,
 59,
 77,
 37,
 38,
 81,
 83,
 97,
 141,
 0,
 99,
 54,
 48,
 32,
 178,
 176,
 146,
 158,
 255,
 45,
 338,
 3,
 348,
 79,
 342,
 154,
 152,
 156,
 331,
 91,
 68,
 174,
 113,
 153,
 35,
 126,
 130,
 142,
 128,
 137,
 411,
 119,
 139,
 129,
 151,
 313,
 140,
 298,
 315,
 271,
 317,
 451,
 278]

In [11]:
#student study before the exam
from typing import Counter
the_data = data.groupby(['UserId','QuizId']).apply(lambda group:(group['UserId'].mean(),group['QuizId'].mean(),(group['IsCorrect'].sum() / group.shape[0]))).reset_index(drop=True)
data_new = pd.DataFrame(the_data.tolist())
columns =['UserId','QuizId','ExamPreparation']
data_new.columns = columns

In [ ]:
data_new.head()

   UserId  QuizId  ExamPreparation
0     0.0   473.0         0.000000
1     0.0   584.0         1.000000
2     0.0   849.0         0.625000
3     0.0  1135.0         0.833333
4     0.0  1299.0         0.714286

In [12]:
data = data.merge(data_new, how='left', on=['UserId','QuizId'])
data.head()

   QuestionId  UserId  AnswerId  ...  Level  Age  ExamPreparation
0       16997   65967  12453206  ...      2   16         0.375000
1       16531   62121  15686710  ...      2   12         0.700000
2       15911   50013  13598796  ...      3   14         0.875000
3        1701  104909  10511925  ...      3   14         0.375000
4       22896   21748    941747  ...      3   13         0.428571

[5 rows x 21 columns]

In [13]:
#overall student score in all questions he/she answed
overall = data.groupby(['UserId']).apply(lambda group:(group['UserId'].mean(),(group['IsCorrect'].sum() / group.shape[0]))).reset_index(drop=True)
overall_pd=pd.DataFrame(overall.tolist())
columns =['UserId','Student performance']
overall_pd.columns = columns

In [14]:
overall_pd.head()

   UserId  Student performance
0     0.0             0.448387
1     1.0             0.800000
2     2.0             0.819672
3     3.0             0.753425
4     4.0             0.524590

In [15]:
data = data.merge(overall_pd, on='UserId', how='left')
data.head()

   QuestionId  UserId  AnswerId  ...  Age  ExamPreparation  Student performance
0       16997   65967  12453206  ...   16         0.375000             0.500000
1       16531   62121  15686710  ...   12         0.700000             0.837209
2       15911   50013  13598796  ...   14         0.875000             0.491228
3        1701  104909  10511925  ...   14         0.375000             0.540541
4       22896   21748    941747  ...   13         0.428571             0.576159

[5 rows x 22 columns]

In [ ]:
#perData for test
perData=[]
perData = data_new

In [ ]:
perData = perData.merge(overall_pd, on='UserId', how='left')

In [ ]:
perData.to_csv('/content/drive/MyDrive/DatasetProject1/perForTest.csv')

In [ ]:
perForTest = pd.read_csv('/content/drive/MyDrive/DatasetProject1/perForTest.csv')

In [ ]:
perData.head()

   UserId  QuizId  ExamPreparation  Student performance
0     0.0   473.0         0.000000             0.448387
1     0.0   584.0         1.000000             0.448387
2     0.0   849.0         0.625000             0.448387
3     0.0  1135.0         0.833333             0.448387
4     0.0  1299.0         0.714286             0.448387

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15867850 entries, 0 to 15867849
Data columns (total 22 columns):
 #   Column               Dtype
---  ------               -----
 0   QuestionId           int64
 1   UserId               int64
 2   AnswerId             int64
 3   IsCorrect            int64
 4   CorrectAnswer        int64
 5   AnswerValue          int64
 6   DateAnswered         datetime64[ns]
 7   GroupId              int64
 8   QuizId               int64
 9   Gender               int64
 10  DateOfBirth          datetime64[ns]
 11  PremiumPupil         float64
 12  SubjectId            int64
 13  SubjectId_1          int64
 14  SubjectId_2          int64
 15  SubjectId_3          float64
 16  SubjectId_4          float64
 17  ParentId             int64
 18  Level                int64
 19  Age                  int64
 20  ExamPreparation      float64
 21  Student performance  float64
dtypes: datetime64[ns](2), float64(5), int64(15)
memory usage: 2.7 GB

In [17]:
data.isnull().sum()

QuestionId                   0
UserId                       0
AnswerId                     0
IsCorrect                    0
CorrectAnswer                0
AnswerValue                  0
DateAnswered                 0
GroupId                      0
QuizId                       0
Gender                       0
DateOfBirth            5093632
PremiumPupil           9904268
SubjectId                    0
SubjectId_1                  0
SubjectId_2                  0
SubjectId_3               3831
SubjectId_4               7122
ParentId                     0
Level                        0
Age                          0
ExamPreparation              0
Student performance          0
dtype: int64

In [ ]:
data = data.drop(['CorrectAnswer','AnswerValue'],axis=1)

In [ ]:
data = data.fillna({'PremiumPupil':0})
data['PremiumPupil']=data['PremiumPupil'].replace(1,0)
data['PremiumPupil']=data['PremiumPupil'].replace(2,1)

In [ ]:
data.to_csv('/content/drive/MyDrive/DatasetProject1/Train_Project1.csv')

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/DatasetProject1/Train_Project1.csv')